### ISSUE TITLE
Error in SOL borrow after I max-withdrew successfully

### ISSUE THREAD

**Issue by KevinRafaelConnor** [jet-lab/jet-v1#100]
Moved from Asana @GHesericsu @eyevz @Tristyn 

![image](https://user-images.githubusercontent.com/89974125/134940980-58a5a6c8-6015-499f-a4ec-6c6d51b4c8cb.png)

rollbar.umd.min.js:1 Transaction simulation failed: Error processing Instruction 4: custom program error: 0x133 
    Program JPv1rCqrhagNNmJVM5J1he7msQ5ybtvE1nNuHpDHMNU invoke [1]
    Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA invoke [2]
    Program log: Instruction: MintTo
    Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA consumed 2883 of 169005 compute units
    Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA success
    Program log: reserve refreshed
    Program JPv1rCqrhagNNmJVM5J1he7msQ5ybtvE1nNuHpDHMNU consumed 34845 of 200000 compute units
    Program JPv1rCqrhagNNmJVM5J1he7msQ5ybtvE1nNuHpDHMNU success
    Program JPv1rCqrhagNNmJVM5J1he7msQ5ybtvE1nNuHpDHMNU invoke [1]
    Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA invoke [2]
    Program log: Instruction: MintTo
    Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA consumed 2883 of 169028 compute units
    Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA success
    Program log: reserve refreshed
    Program JPv1rCqrhagNNmJVM5J1he7msQ5ybtvE1nNuHpDHMNU consumed 34822 of 200000 compute units
    Program JPv1rCqrhagNNmJVM5J1he7msQ5ybtvE1nNuHpDHMNU success
    Program JPv1rCqrhagNNmJVM5J1he7msQ5ybtvE1nNuHpDHMNU invoke [1]
    Program log: reserve refreshed
    Program JPv1rCqrhagNNmJVM5J1he7msQ5ybtvE1nNuHpDHMNU consumed 26208 of 200000 compute units
    Program JPv1rCqrhagNNmJVM5J1he7msQ5ybtvE1nNuHpDHMNU success
    Program JPv1rCqrhagNNmJVM5J1he7msQ5ybtvE1nNuHpDHMNU invoke [1]
    Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA invoke [2]
    Program log: Instruction: MintTo
    Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA consumed 2883 of 169330 compute units
    Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA success
    Program log: reserve refreshed
    Program JPv1rCqrhagNNmJVM5J1he7msQ5ybtvE1nNuHpDHMNU consumed 34520 of 200000 compute units
    Program JPv1rCqrhagNNmJVM5J1he7msQ5ybtvE1nNuHpDHMNU success
    Program JPv1rCqrhagNNmJVM5J1he7msQ5ybtvE1nNuHpDHMNU invoke [1]
    Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA invoke [2]
    Program log: Instruction: MintTo
    Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA consumed 2883 of 184717 compute units
    Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA success
    Program log: Custom program error: 0x133
    Program JPv1rCqrhagNNmJVM5J1he7msQ5ybtvE1nNuHpDHMNU consumed 21253 of 200000 compute units
    Program JPv1rCqrhagNNmJVM5J1he7msQ5ybtvE1nNuHpDHMNU failed: custom program error: 0x133
e.<computed> @ rollbar.umd.min.js:1
sendEncodedTransaction @ index.browser.esm.js:4809
async function (async)
sendEncodedTransaction @ index.browser.esm.js:4797
sendRawTransaction @ index.browser.esm.js:4772
sendAllTransactions @ programUtil.ts:267
async function (async)
sendAllTransactions @ programUtil.ts:237
borrow @ jet.ts:475
async function (async)
borrow @ jet.ts:405
(anonymous) @ Cockpit.svelte:352
(anonymous) @ ReserveDetail.svelte:17
f @ ReserveDetail.svelte:17
U @ Cockpit.svelte:283
D @ Cockpit.svelte:277
R.abbrev.i.abbrev.p @ Cockpit.svelte:435
rollbar.umd.min.js:1 Borrow error: Error: failed to send transaction: Transaction simulation failed: Error processing Instruction 4: custom program error: 0x133

**Comment by LanfordCai** [comment]
Same in ETH，borrow transaction would be failed if I max-withdrew ETH before borrowing.

**Comment by Tristyn** [comment]
This has been fixed recently, please reopen if you observe it again :)
