### ISSUE TITLE
SOL airdrop not work but still remind me "Success"

### ISSUE THREAD

**Issue by LanfordCai** [jet-lab/jet-v1#118]
![image](https://user-images.githubusercontent.com/10380321/135266186-0cd0a56a-939f-4593-9ac5-01d4aad7bed3.png)

But I didn't get any SOL.

**Comment by wilbarnes** [comment]
good catch thank u, will fix

the airdrop is failing because the max airdrop amount on devnet was decreased from 10 to 1 and we just haven't updated the error msgs yet

**Comment by GAUTAMRAJU15** [comment]
> ![image](https://user-images.githubusercontent.com/10380321/135266186-0cd0a56a-939f-4593-9ac5-01d4aad7bed3.png)
> 
> But I didn't get any SOL.

in the mean time you can use solana cli to fund yourself some devnet token
