### ISSUE TITLE
Borrowed Amount is less than its real value

### ISSUE THREAD

**Issue by LanfordCai** [jet-lab/jet-v1#119]
![image](https://user-images.githubusercontent.com/10380321/135278359-ee95e40c-8396-4e30-84a9-9bbe54eeb24f.png)

I borrowed 10 ETH, and my wallet get 10 ETH, but the UI shown that the borrowed value is less than 10 ETH. When I try to repay 10 ETH I got error like this:

![image](https://user-images.githubusercontent.com/10380321/135278991-e1825ce5-a662-4d21-8fa4-808e88b9dd0a.png)

The gap may make the depositors suffered from loss?

**Comment by Tristyn** [comment]
The contract now rounds in the pools favor, depositors in this case. Please reopen if you see this issue again.

**Comment by Tristyn** [comment]
In this instance your borrowed amount should be = 1 or slightly > 1
