### ISSUE TITLE
Display a warning for insufficient SOL in wallet to complete transaction

### ISSUE THREAD

**Issue by LanfordCai** [jet-lab/jet-v1#120]
![image](https://user-images.githubusercontent.com/10380321/135280055-18f02c7d-9b33-4153-a9fa-8d90f66fd94d.png)
The only information I got is 👆

Finally I find out the reason: there is no enough SOL in my wallet -- I have 0.028 SOL in my wallet, but it's not enough, it seems Jet is a bit expensive.

I think this kind of error(SOL not enough) should be show to users.

**Comment by Tristyn** [comment]
The firs transactions for a reserve are expensive because Jet has to open new accounts for you, yes

**Comment by KevinRafaelConnor** [comment]
Closing this because we are working on displaying this cost for users in this issue: https://github.com/jet-lab/jet-v1/issues/232
