### ISSUE TITLE
Show connected wallet's first and last 4 pubkey characters in the header (not just in settings)

### ISSUE THREAD

**Issue by KevinRafaelConnor** [jet-lab/jet-v1#121]
It should also allow disconnecting that wallet by clicking and include hover text "Disconnect Wallet" (just like in in the settings sidebar)

Also personally I think is clearer if the hover text says "Click to Disconnect Wallet" in both cases but maybe I am splitting hairs here

**Comment by holross** [comment]
Wallet moved to new place in cockpit, top right and now includes pubkey characters. Tooltip hover for disconnect. @loganjross 

<img width="998" alt="Screen Shot 2021-10-05 at 8 57 26 PM" src="https://user-images.githubusercontent.com/91745209/136124094-8885cb8d-b323-4c59-8280-2a6e037ea410.png">
