### ISSUE TITLE
Modal is shown to deposit/borrow even when the state of button is disabled

### ISSUE THREAD

**Issue by GAUTAMRAJU15** [jet-lab/jet-v1#135]
The modal that asks for confirmation shouldn't be shown in UI if  I can't borrow or deposit in the protocol. But it is still being shown.

### How to reproduce
1. Click on arrow button while button is disabled.
2. Modal pops up.

![Screenshot_2021-09-29_at_9 43 57_PM](https://user-images.githubusercontent.com/13881992/135409815-f579151e-8277-4ce8-b09d-bec93c11c67a.png)

![Screenshot_2021-09-29_at_9 44 51_PM](https://user-images.githubusercontent.com/13881992/135409818-d9b8e0a3-6c00-4efd-a380-cb589dc8909a.png)

**Comment by KevinRafaelConnor** [comment]
Even when the modal is not applicable and does not pop up, the input field populates with red text "Enter amount." even though the fields are disabled and clicking the arrow should do nothing. 

Thanks for opening the issue here @GAUTAMRAJU15

**Comment by GHesericsu** [comment]
@KevinRafaelConnor I can fix this one.

**Comment by loganjross** [comment]
Taken care of!
