### ISSUE TITLE
The "?" icons that define "C-Ratio" and "Liquidation Premium" are too small and unclear

### ISSUE THREAD

**Issue by KevinRafaelConnor** [jet-lab/jet-v1#141]
From #ux-ui-improvements in Discord. 

In "asset details" and the c-ratio in the top-right, the "?" button is tiny and has no hover text so it isn't clear they should click it.

Make it larger and consider having a tiny hover blurb ie "click for more info!"

**Comment by holross** [comment]
Implement tooltip popup that just says "what is this?" over all ⓘ icons to cue viewers to click for info @loganjross 

<img width="533" alt="Screen Shot 2021-10-05 at 3 29 42 PM" src="https://user-images.githubusercontent.com/91745209/136090207-e9efd5a2-47b1-486e-bf19-e4f10755e38c.png">
