### ISSUE TITLE
Make the text clearer and more spaced when clicking "?"s for more info

### ISSUE THREAD

**Issue by KevinRafaelConnor** [jet-lab/jet-v1#142]
From #ux-ui-improvements in Discord. 

When clicking "?" for more info anywhere, the resulting text description should have a slightly larger font and the lines between text be spaced more; it's helpful information but quite claustrophobic / difficult to read as noted by several users.

**Comment by holross** [comment]
New modal layout @loganjross 

<img width="499" alt="Screen Shot 2021-10-05 at 5 14 09 PM" src="https://user-images.githubusercontent.com/91745209/136103630-4f673504-da0c-4d11-9dd1-78e785ff0e50.png">

**Comment by KevinRafaelConnor** [comment]
They will love it.
