### ISSUE TITLE
Can't pay the loan

### ISSUE THREAD

**Issue by son15119195** [jet-lab/jet-v1#166]
I deposited 1 SOL into the protocol and then I borrowed $50. When I wanted to pay the full amount, I couldn't. It reports an error. My connection is fine. I confirm there is enough USDC in my wallet because I haven't brought it anywhere, I just connected to your JET protocol
![lỗi JET](https://user-images.githubusercontent.com/82816627/135778155-7a4a1149-8141-4a47-a9b2-fa2c04aa6ce6.png)

**Comment by KevinRafaelConnor** [comment]
Hi @son15119195, thanks for testing and opening an issue! 

We’ve just deployed a series of fixes to this bug that you experienced  - check it out! If it persists, try it with a new wallet -- some of the problems were due to account issues and won't happen anymore going forward.
