### ISSUE TITLE
Numerical fields do not consistently update until clicking in the table, after deposit/withdraw/borrow/repay/airdrop

### ISSUE THREAD

**Issue by KevinRafaelConnor** [jet-lab/jet-v1#167]
After a transaction goes through successfully, the relevant numerical fields to change (available liquidity, wallet balance, deposited, and/or borrowed) does not consistently update until a mouse click event somewhere in the table.

It is inconsistent -- sometimes, some of the fields update, sometimes all that should do, sometimes 1/3 that should do.

Please speak with @Tristyn for more details -- He told me this is related to when we choose to redraw the UI.

**Comment by loganjross** [comment]
Should be fixed
