### ISSUE TITLE
About UI

### ISSUE THREAD

**Issue by qinchenhui** [jet-lab/jet-v1#18]
Deposit, withdraw, borrow and repair are the main function buttons, but they are not very obvious. I even looked for them for a while before I saw them. 
![Jet-Protocol-Cockpit](https://user-images.githubusercontent.com/31091991/133453457-33827a76-ba4d-4c7f-9c09-2df13b88451d.png)

**Comment by antoniomc27** [comment]
I agree with that comment from qinchenhui. For me, the info button next to the C-ratio is also too small to be noticed.
![image](https://user-images.githubusercontent.com/11273874/133470386-b5ed94c8-b231-4a8b-bc79-e66d301414ce.png)

**Comment by GHesericsu** [comment]
This is noted. Thank you for the feedback!
