### ISSUE TITLE
Error when repaying max USDC

### ISSUE THREAD

**Issue by KevinRafaelConnor** [jet-lab/jet-v1#182]
My steps to reproduce:

1. Create new wallet
2. Airdrop 1 SOL
3. Deposit 0.7 SOL
4. Borrow 44 USDC (I borrowed a "safe" amount with c-ratio = ~178% after the borrow)
5. Repay USDC, clicking MAX button

Note that when I repayed USDC by typing in 44 manually, it succeeded. Then there is still dust remaining; "borrowed" column shows ~0 (see pic below) which is fine. But when I try to pay back the dust with the max button, it again breaks.

I did NOT have the same issue with borrowing/repaying max BTC and ETH.

![image](https://user-images.githubusercontent.com/89974125/136169631-7f47e1dd-1e81-426f-8189-2bfe6a00d025.png)

**Comment by Tristyn** [comment]
>Then there is still dust remaining; "borrowed" column shows ~0 (see pic below) which is fine. But when I try to pay back the dust with the max button, it again breaks.

This part, paying back with the max button should be fixed now
