### ISSUE TITLE
Toggle for currency denomination is too small to view in screen

### ISSUE THREAD

**Issue by jrmoreau** [jet-lab/jet-v1#2]
user submitted feedback - I agree it's hard to see what this button does - it's not obvious

<img width="1098" alt="Screen Shot 2021-09-13 at 16 44 55" src="https://user-images.githubusercontent.com/1614127/133153872-1fe8659a-a860-4564-b6e2-35edf7e85f54.png">

**Comment by KevinRafaelConnor** [comment]
Let's make this bigger and more visible and also add a descriptive tooltip; something like "Toggle cryptocurrency versus USD denomination"

**Comment by holross** [comment]
I know this is closed, but adding my 2 cents:

Solution A: 85% transparency tooltip that pops up after a second when hovering
Solution B: Add words to toggle beside icon if tooltip isn't possible

<img width="575" alt="Screen Shot 2021-10-05 at 3 19 56 PM" src="https://user-images.githubusercontent.com/91745209/136088986-845990d7-0231-4709-bc0a-0ae38a4d65f2.png">
<img width="453" alt="Screen Shot 2021-10-05 at 3 06 52 PM" src="https://user-images.githubusercontent.com/91745209/136089016-6a69634a-a2fa-4c8c-87ba-c5fa13f6c843.png">

**Comment by KevinRafaelConnor** [comment]
Totally, love the backup plan.
