### ISSUE TITLE
Settings button does not work

### ISSUE THREAD

**Issue by antoniomc27** [jet-lab/jet-v1#21]
When you click settings, it redirects to URL https://devnet.jetprotocol.io/settings, but screen is unresponsive, you keep staying in the "cockpit"

![image](https://user-images.githubusercontent.com/11273874/133470862-141c56c7-e992-4c27-8e76-5b9ff171c874.png)

**Comment by GHesericsu** [comment]
Are you still having this issue? I'm not able to reproduce this bug. And I have not seen it reported anywhere else.

**Comment by antoniomc27** [comment]
I checked today and now the settings button works for me. Unsure why it happened last time. Sorry!

**Comment by GHesericsu** [comment]
:)
