### ISSUE TITLE
Animate sidebar on initial load from to expanded, so it is more obvious they have that option

### ISSUE THREAD

**Issue by KevinRafaelConnor** [jet-lab/jet-v1#258]
As discussed as a compromise for now in #235

**Comment by holross** [comment]
Adding @loganjross to tell us what he can whip up on the technical end. I see it basically looking like oyster's sidebar collapse animation, but it could just do that right on first load. 

So, on launch the sidebar is expanded, wait like 2 or 3 seconds, then it animates to collapsed position until someone manually expands again.

**Comment by loganjross** [comment]
there currently is no transition to sidebar, and in terms of design we prefer the collapsed nav. this one to me falls into the whole "making it blatantly obvious" thing which would require design changes so that there is a smooth transition animation
