### ISSUE TITLE
Error processing Instruction 2: custom program error when declare_id!(programid) was changed

### ISSUE THREAD

**Issue by impraveen-chouhan** [jet-lab/jet-v1#305]
We follow some steps:
1) created new keygen "lending.json"
https://github.com/solana-labs/solana-program-library/tree/master/token-lending
2) Now we used replace declare_id!() with our public key address of "lending.json" inside /jet-v1/programs/jet/src/lib.rs 
3) cargo build , and cargo build-bpf
4) generated program-id as same of "lending.json"
5) npm run dev
6) click on deposit

Now we got below error.
Please let me know, if anyone have any solution. 

rollbar.umd.min.js:1 Transaction simulation failed: Error processing Instruction 2: custom program error: 0xa7 
    Program 11111111111111111111111111111111 invoke [1]
    Program 11111111111111111111111111111111 success
    Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA invoke [1]
    Program log: Instruction: InitializeAccount
    Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA consumed 3680 of 200000 compute units
    Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA success
    Program EVPfMQgLW9asgnZwCp1fx7qHMnQGUesRMu4m4dRZxz9g invoke [1]
    Program log: Custom program error: 0xa7
    Program EVPfMQgLW9asgnZwCp1fx7qHMnQGUesRMu4m4dRZxz9g consumed 3145 of 200000 compute units
    Program EVPfMQgLW9asgnZwCp1fx7qHMnQGUesRMu4m4dRZxz9g failed: custom program error: 0xa7

![Screenshot from 2021-10-26 21-01-45](https://user-images.githubusercontent.com/59281102/138912076-b7869dc6-c90b-4e9f-bfd5-5a43ade36ca7.png)

**Comment by francesco-gaglione** [comment]
I think that anchor works like hardhat on Etherium, that mean that the command anchor deploy not work to your localnet as default, instead it will create it's own "chain". I tryed it and your commands works but in the 4th command u have to use: 

```
 anchor deploy --provider.cluster localnet
```
