### ISSUE TITLE
Mobile mode is easily triggered by narrower width on desktop browser. 

### ISSUE THREAD

**Issue by GHesericsu** [jet-lab/jet-v1#308]
This has tricked a few users thinking they could only connect with Sollet as some people use narrowed screen size on desktop or have multiple windows open on one screen. 

Fix 1: Show users that they're on Mobile Mode on the dashboard and wallet modal. And we only support Sollet and Slope on mobile. Use desktop for a better experience. 

Fix 2: Use a different method to detect mobile user or make the width to trigger mobile mode narrower.

**Comment by holross** [comment]
From design standpoint, I'd like to avoid actually telling people they're on mobile mode if possible. Let's see if logan can do something more along the lines of Fix 2 @loganjross
