### ISSUE TITLE
Show exact amount numbers optionally

### ISSUE THREAD

**Issue by GHesericsu** [jet-lab/jet-v1#309]
iwearahoodie#7661 suggested he needs to see the exact numbers to do calculation and see what we can do. 

Idea: Show exact amount numbers on hover.

**Comment by holross** [comment]
Agree, really good feedback. We'll get rid of rounding in that area and for styling, let the div grow with long numbers if necessary @loganjross

**Comment by loganjross** [comment]
Done, let's inform user of change and thank them for feedback @GHesericsu

**Comment by loganjross** [comment]
@iwearahoodie We've made this change! Thanks so much for your great feedback
