### ISSUE TITLE
After deposit cannot max withdraw, cannot borrow

### ISSUE THREAD

**Issue by hellomesh** [jet-lab/jet-v1#32]
I did deposit, directly try to borrow= failed,
try to withdraw max ammount= failed, try to withdraw less ammount =success (for example the max ammount appear 200 SOL, you only can withdraw 199 for successful trx)
after that i tried to borrow, and this text appear 'you deposit token and you can't borrow it', even i tried with other 0 token deposited (see picture).
![jetprot](https://user-images.githubusercontent.com/90819301/133562988-8f0469d9-381a-429d-b683-2b08ec22fbd4.JPG)

**Comment by baccaridj** [comment]
Same issue here
![Uploading Screenshot_20210916-063302.png…]()

**Comment by GHesericsu** [comment]
We're fixing the max-withdraw bug.

**Comment by wheeljax** [comment]
same issue found for all coins
