### ISSUE TITLE
unreachable code?

### ISSUE THREAD

**Issue by ilmoi** [jet-lab/jet-v1#356]
I might be mistaken, but I think in the below code:

https://github.com/jet-lab/jet-v1/blob/b2be349ab5e0a5804e2b79e54638f3459c8101fb/libraries/math/src/number.rs#L38-L49

this bit in unreachable:
```
if extra_precision < 0 { 
     prec_value = ONE / prec_value; 
 } 
```

the reason I think that is because `ten_pow` will throw an error if it gets anything below 0:
https://github.com/jet-lab/jet-v1/blob/b2be349ab5e0a5804e2b79e54638f3459c8101fb/libraries/math/src/number.rs#L141-L164

I'm not sure if this is a problem / matters at all - just something I spotted and thought would share. Feel free to close if not important.

**Comment by nevi-me** [comment]
Hi @ilmoi, it's still reachable because `Self::ten_pow(extra_precision.abs() as u32);` takes an absolute value. So `let extra_precision = -16` will still work as we check `len_pow(16)`, then we get `prec_value` as 1/-16

**Comment by ilmoi** [comment]
lol totally my bad. Thanks for pointing out 🙏
