### ISSUE TITLE
log the IMU and PWM outputs at the same timestamp in pixhawk 4 mini

### ISSUE THREAD

**Issue by ghost** [jet-lab/jet-v1#365]
Hi I am research student ,
actually to find the inertial tensor I need IMU gyro and PWM outputs values with timestamp for this how can I boost the logging data to 400HZ. The log which is generated in QGC is limited to 50HZ but I need these values at which rate the pix hawk generates the signal. so can anyone help to log the IMU gyro and PWM outputs at its maximum rate . so that it is easy for me to find the inertial tensor.

http://docs.px4.io/master/en/dev_log/logging.html#logging

and by doing the above one I am getting at high rate but the time stamp on IMU gyro and PWM outputs does not match, GYRO and PWM generates randomly irrespective of the time between two values are not same

**Comment by eyevz** [comment]
Risky click 😂  In case this isn't a phish, you are in the wrong place, friend.

**Comment by wilbarnes** [comment]
interesting, i removed the hyperlink
