### ISSUE TITLE
Contributing instructions

### ISSUE THREAD

**Issue by francesco-gaglione** [jet-lab/jet-v1#366]
I'm very interested in contributing and reading the main page README I'm really confused. The build indication is quite good but there aren't indications on the branches lifecycles and there are a lot of branches with different names. Probably it could be a good strategy to define which branch is supposed to be, with a good description in the main page README or into a new CONTRIBUTING.md file with all the instructions.

In the meantime on which branch can I help to solve some issues? And the process is to open a new pull request from a personal fork or can I work on the main repo?

Thk to all

**Comment by qiqicodes** [comment]
@francesco-gaglione Thank you for your interests and feedbacks in regards to contributing. 

Currently we are figuring out our formalized process for contributing, due to the risks involved.

Stay posted with our updates.

**Comment by francesco-gaglione** [comment]
Thk to u @qiqicodes. In the maintime I created a pull request. It's a very simple feature. I added my language translations so the dapp can be used in my country too. But I sow that part of the automated build failed, but the cause is not my code editing. Is it normal? The pull request can be merged?

P.S.: I should close this issue or leave it open waiting for development documentation?

**Comment by qiqicodes** [comment]
@francesco-gaglione feel free to leave the issue open for now. 

I'm currently reviewing your pr. the translation looks very good and the build is successful.
