### ISSUE TITLE
Flight logs aren't loading older transaction history

### ISSUE THREAD

**Issue by float1hope** [jet-lab/jet-v1#396]
Clicking the "Load More" button ends up concating the same transactions to the initally loaded ones.

Also I had a liquidation event in the given time range, which is not in the flight logs

![Bildschirmfoto_vom_2022-04-19_18-43-38](https://user-images.githubusercontent.com/104225689/164777660-e2f685c6-095f-4930-ad5b-4a2c6bda1cbb.png)
.

**Comment by GHesericsu** [comment]
The fix will be merged soon.

**Comment by float1hope** [comment]
awesome

**Comment by float1hope** [comment]
Is this one already merged? I can't see any changes on this. There is still the same occurrence like in the picture above
