### ISSUE TITLE
Unable to deposit

### ISSUE THREAD

**Issue by jue1158** [jet-lab/jet-v1#54]
Unable to deposit

**Comment by tientaidev** [comment]
Same with me 
![Screenshot 2021-09-19 at 12 19 25](https://user-images.githubusercontent.com/43933775/133916405-0d715ca7-0ec7-497c-b719-8980fa9718c8.png)

**Comment by GHesericsu** [comment]
This will be fixed in the next merge within a day. Thank you.

**Comment by GHesericsu** [comment]
should be able to deposit now
