### ISSUE TITLE
Can't deposit

### ISSUE THREAD

**Issue by duytu181** [jet-lab/jet-v1#56]
I can't deposit my testnet asset.

**Comment by LanfordCai** [comment]
Yeah, it reports Too Big Number, even only 1 SOL.
![image](https://user-images.githubusercontent.com/10380321/133915892-ba62134b-6bfb-4f54-8aa3-9e9898a7896c.png)

**Comment by GHesericsu** [comment]
This will be fixed in the next merge within a day. Thank you.

**Comment by GHesericsu** [comment]
should be able to deposit now.
