### ISSUE TITLE
airdrop Transaction failed.

### ISSUE THREAD

**Issue by Hututu316** [jet-lab/jet-v1#65]
![image](https://user-images.githubusercontent.com/73937557/134194532-9ada79aa-c82f-443a-8f52-5a5677d43883.png)

![image](https://user-images.githubusercontent.com/73937557/134194342-444e31e3-69ae-4fbd-bcf4-0dcc5e82e69d.png)

**Comment by GHesericsu** [comment]
This is Solana disabling its devnet airdrop for anyone.
