### ISSUE TITLE
Loan repayment bug 5CBGqfDLN6eDk4GtRoy2UcSckDXqzHH4kAozjWr2wq3P

### ISSUE THREAD

**Issue by Bezalel12** [jet-lab/jet-v1#78]
![Screenshot_2021-09-23-08-05-58-928_com android chrome](https://user-images.githubusercontent.com/90438915/134473539-8a695891-75a1-4b87-b733-b92917a316ea.jpg)
![Screenshot_2021-09-23-08-05-41-861_com android chrome](https://user-images.githubusercontent.com/90438915/134473545-0acefa30-c9d4-4db9-9efa-ad2725c1838d.jpg)

After completing payment for the loan, it's displaying I still have a loan to repay

**Comment by GHesericsu** [comment]
We fixed it. just waiting for redeployment today. Thank you!

**Comment by Bezalel12** [comment]
Great. It has been fixed indeed.👍
