### ISSUE TITLE
[MAX button -> DEPOSIT, REPAY] The transaction cannot finish

### ISSUE THREAD

**Issue by dangquangminh-vn** [jet-lab/jet-v1#79]
Address wallet (Sollet):
daw3LEYcWRtsr93gYrtfZR3PLfE9RnusYcBtVq6T7np

**ISSUE:**
At step REPAY -> Click on button MAX -> Submit

Actual result:
When click on button MAX, the returned value is the same as value of BORROWED. The transaction cannot finish

Expected:
When user click on MAX buttons (DEPOSIT, REPAY,...), the returned value should be calulated automatically (included fee), not maximum at the moment

Image:
https://prnt.sc/1tbfpbt

**Comment by GHesericsu** [comment]
We fixed it. just waiting for redeployment today. Thank you!
