### ISSUE TITLE
The "Mayday Transaction failed..." dialog always display when Submit

### ISSUE THREAD

**Issue by dangquangminh-vn** [jet-lab/jet-v1#80]
Address wallet (Sollet):
daw3LEYcWRtsr93gYrtfZR3PLfE9RnusYcBtVq6T7np

Steps:
1. At WITHDRAW, enter **INVALID** value "Number + Character". Ex: 10a
2. Click Submit -> Display a message box "Mayday Transaction failed..."
3. Enter VALID value again
4. Click Submit

Actual result:
The "Mayday Transaction failed..." dialog always display when Submit

**Comment by GHesericsu** [comment]
We fixed it. just waiting for redeployment today. Thank you!
