### ISSUE TITLE
Withdrawal error occurs many times

### ISSUE THREAD

**Issue by donalmie** [jet-lab/jet-v1#91]
After depositing the mortgage and doing other operations are both great and fast. However, withdrawing money back often shows an error, not only once but many times. I had to disconnect from the wallet and start over. So it was quite inconvenient. Hopefully the Jet Protocol project development team will fix it soon. I really believe in the project and definitely invest in your project. Thank you very much!
![Screenshot (14)](https://user-images.githubusercontent.com/91397104/134789777-616ef4d3-b4b6-4760-aa0a-863c045e9404.png)

**Comment by GHesericsu** [comment]
fixed
