### ISSUE TITLE
Phantom extension not loading

### ISSUE THREAD

**Issue by Bezalel12** [jet-lab/jet-v1#92]
Tried  testing with phantom wallet(web extension) but it does not work nor load as at this time.

**Comment by KevinRafaelConnor** [comment]
Hi @Bezalel12, I have been using Phantom app and connecting without issue. 

Is is still not working? Which browser are you using? Are you by chance using a translator app or any other application on the webpage (this has been known to cause issues)?

**Comment by Bezalel12** [comment]
Hello.
I used it with kiwi browser. It is working fine now.
