### ISSUE TITLE
I can't borrow money

### ISSUE THREAD

**Issue by cuongbadao** [jet-lab/jet-v1#96]
i borrowed 100 usdc but failed and it showed this message. when i reset the web and do it ![Untitled](https://user-images.githubusercontent.com/91457462/134867210-a9ddb8c3-1e71-4b46-ad35-b20f090d40eb.png) it works
my wallet : 2J9pc4rduwKZh9sJPVLzL6cGNsqhb7PdLfHMNWZLVr7M

**Comment by KevinRafaelConnor** [comment]
Hello @cuongbadao, which collateral did you deposit before trying to borrow USDC? Are you sure there was available liquidity of USDC to borrow? I was just able to do it several times without any problems. Thanks!
